federation_version: =2.8.0
subgraphs:
  workflows:
    routing_url: https://workflows.diamond.ac.uk/graphql
    schema:
      file: schema/workflows.graphql
  samples:
    routing_url: https://sample-information.diamond.ac.uk/api/graphql
    schema:
      file: schema/samples.graphql
